Traceback (most recent call last):
  File "/Users/deepak/opt/anaconda3/envs/sparkbook/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/deepak/opt/anaconda3/envs/sparkbook/lib/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/deepak/opt/anaconda3/envs/sparkbook/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/deepak/opt/anaconda3/envs/sparkbook/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/deepak/opt/anaconda3/envs/sparkbook/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/deepak/opt/anaconda3/envs/sparkbook/lib/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/Users/deepak/opt/anaconda3/envs/sparkbook/lib/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/deepak/opt/anaconda3/envs/sparkbook/lib/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
df.agg("sales")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAssertionError[0m                            Traceback (most recent call last)
[0;32m<ipython-input-11-0ca02063a9ff>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mdf[0m[0;34m.[0m[0magg[0m[0;34m([0m[0;34m"sales"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m~/opt/anaconda3/envs/sparkbook/lib/python3.8/site-packages/pyspark/sql/dataframe.py[0m in [0;36magg[0;34m(self, *exprs)[0m
[1;32m   1544[0m         [0;34m[[0m[0mRow[0m[0;34m([0m[0mmin[0m[0;34m([0m[0mage[0m[0;34m)[0m[0;34m=[0m[0;36m2[0m[0;34m)[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m   1545[0m         """
[0;32m-> 1546[0;31m         [0;32mreturn[0m [0mself[0m[0;34m.[0m[0mgroupBy[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0magg[0m[0;34m([0m[0;34m*[0m[0mexprs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1547[0m [0;34m[0m[0m
[1;32m   1548[0m     [0;34m@[0m[0msince[0m[0;34m([0m[0;36m2.0[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/envs/sparkbook/lib/python3.8/site-packages/pyspark/sql/group.py[0m in [0;36magg[0;34m(self, *exprs)[0m
[1;32m    110[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    111[0m             [0;31m# Columns[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 112[0;31m             [0;32massert[0m [0mall[0m[0;34m([0m[0misinstance[0m[0;34m([0m[0mc[0m[0;34m,[0m [0mColumn[0m[0;34m)[0m [0;32mfor[0m [0mc[0m [0;32min[0m [0mexprs[0m[0;34m)[0m[0;34m,[0m [0;34m"all exprs should be Column"[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    113[0m             jdf = self._jgd.agg(exprs[0]._jc,
[1;32m    114[0m                                 _to_seq(self.sql_ctx._sc, [c._jc for c in exprs[1:]]))

[0;31mAssertionError[0m: all exprs should be Column
AssertionError: all exprs should be Column

